### ISSUE TITLE
About the accuracy

### ISSUE THREAD

**Issue by ZhouAo-ZA** [bramton/pyg-dgcnn#1]
Hello！
I am also trying to reproduce DGCNN based on PYG, but the accuracy is not up to the one reported in the paper. 
I tried your code, and the highest is only 92%. Can you achieve the accuracy reported in the paper?

**Comment by bramton** [comment]
Indeed, my accuracy is also limited to 92% at the moment. I have made a few minor corrections to the code, the accuracy should be a tad higher now. I noticed the original code also uses a pre-processed ModelNet40 dataset, I will also try to use this dataset instead of the one provided by PyG. Let me know if you are able to achieve the accuracy mentioned in the paper, I am curious.

**Comment by bramton** [comment]
With a few more edits, I was able to achieve the same accuracy as the paper. 

Also see my PR to the torch_geometric library [here](https://github.com/pyg-team/pytorch_geometric/pull/4981)

**Comment by ZhouAo-ZA** [comment]
It is worked, thanks for sharing!
